// <auto-generated />
using System;
using Calculator.Infrastracture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculator.Infrastracture.Migrations
{
    [DbContext(typeof(CalculatorDBContext))]
    partial class CalculatorDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Calculator.Infrastracture.Database.Tables.CalculateHistories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LeftOperand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RightOperand")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Calculates");
                });
#pragma warning restore 612, 618
        }
    }
}
